"""add price column

Revision ID: a6164536e9d1
Revises: e2e091996f1f
Create Date: 2025-11-27 11:25:02.187886

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a6164536e9d1"
down_revision = "e2e091996f1f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entry", schema=None) as batch_op:
        batch_op.add_column(sa.Column("price", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entry", schema=None) as batch_op:
        batch_op.drop_column("price")

    # ### end Alembic commands ###
